name: Test CI

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"

      - name: Run tests
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: test
          gradle-home-cache-cleanup: true